name: Rockypoint
favicon: null
layout_spectrum: 0.74749
typography_spectrum: 0.06407
title: Rockypoint.org
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#6593ce'
    - '#554546'
    - '#b6ceed'
    - '#fff5e9'
    - '#e55a1e'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
