name: Rockypoint
favicon: null
layout_spectrum: 0.3794
typography_spectrum: 0.06155
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#93b1cd'
    - '#171a1f'
    - '#65809d'
    - '#dfdee3'
    - '#4b4c50'
  brandStrength: 0.75
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
