name: Rockypoint
favicon: null
layout_spectrum: 0
typography_spectrum: 0.70582
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#322515'
    - '#ffffff'
    - '#595441'
    - '#8e8969'
    - '#dcbc83'
  brandStrength: 0.8125
  lightness: 0.3513789821881801
  saturation: 0.7433844895567745
  rhythmicContrast: 0.8384141030255705
purpose: []
