name: Rockypoint
favicon: null
layout_spectrum: 0.53125
typography_spectrum: 0.9338821498677135
title: Gorgeous Mexican Paradise
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#322515'
    - '#ffffff'
    - '#595441'
    - '#8e8969'
    - '#dcbc83'
  brandStrength: 0.75
  lightness: 0.7061663372442126
  saturation: 0.873676986200735
  rhythmicContrast: 0.8142217707354575
purpose: []
