title: Rockypoint.org
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 0.6407089
  brandStrength: 0.5
  lightness: 0.7599356
  brandColors:
    - '#ffffff'
  rhythmicContrast: 0.6901182
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: Rockypoint
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.5676692
layout_spectrum: 0.74749
