name: Rockypoint
favicon: null
layout_spectrum: 0.74749
typography_spectrum: 0.06407
title: Rockypoint.org
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#0b0b0b'
    - '#ab9a80'
    - '#4a5b6b'
    - '#dbc5ad'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.875
  rhythmicContrast: 0.5
purpose: []
